package com.ssafy.b109.aivo.rabbitmq.entity;

public enum AnalysisEventType {
    PRESENTATION_FEEDBACK_REQUEST,
    PRESENTATION_QUESTION_GENERATE_REQUEST,
    PRESENTATION_QUESTION_FEEDBACK_REQUEST,
    AUDIO_ANALYSIS_REQUEST
}